import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "supabase/**",
      // Generated by Next on every build; its triple-slash references
      // trip @typescript-eslint/triple-slash-reference. Not our code.
      "next-env.d.ts",
    ],
  },
];

export default config;
